# Generated by Django 3.2.13 on 2022-09-17 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_type', models.CharField(max_length=50, verbose_name='Название типа консоли')),
            ],
            options={
                'verbose_name': 'Тип консолей',
                'verbose_name_plural': 'Типы консолей',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото')),
                ('is_exists', models.BooleanField(default=False, verbose_name='Есть ли в наличии')),
                ('slug_product', models.CharField(max_length=200, verbose_name='Ссылка на категорию')),
                ('product_type_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producttype', verbose_name='К какому типу относится')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
